#!/bin/bash
set -euo pipefail
export IGNORE_QSCRIPTS=true

# shellcheck source=../get-latest-version
source "${BASH_SOURCE[0]%/*}"/../get-latest-version

qURL https://aur.archlinux.org/rar.git | sed 's#\.##'
