#!/bin/bash
set -euo pipefail
[ "${IGNORE_QSCRIPTS:-null}" = true ] || IGNORE_QSCRIPTS=false

query_aur () {
    local url="${1}"
    local pkgver="null"
    local tmpdir
    tmpdir="$(mktemp -d)"

    git clone --quiet --depth=1 "$url" "$tmpdir"

    # shellcheck disable=1091
    source "${tmpdir}/PKGBUILD" || :
    echo "${pkgver}"
}

query_github_release () {
    local url="${1/github.com/api.github.com/repos}/releases/latest"
    curl -s "$url" | jq -r .tag_name | sed 's%^[rv]%%'
}

query_github_tag () {
    local url="${1/github.com/api.github.com/repos}/tags"
    curl -s "$url" | jq -r '.[0].name' | sed 's%^[rv]%%'
}

# Actions

qURL () {
    local url="$1"

    case "$url" in
        https://github.com/?*) query_github_tag "$url" ;;
        https://aur.archlinux.org/?*.git) query_aur "$url" ;;
    esac
}

qAnitya () {
    local project="$1"
    curl -s "https://release-monitoring.org/api/v2/projects/?name=${project}" | jq -r '.items[0].stable_versions[0]'
}

# ### Main Function
VersionQuery () {
    local pkg entry

    for entry in "$@"; do
        pkg="${entry##*/}"
        ! $IGNORE_QSCRIPTS && [ -x "${0%/*}/VersionQuery/$pkg" ] && exec "${0%/*}/VersionQuery/$pkg"

        case "$entry" in
            http://?*|https://?*) qURL "$entry" ;;
            ?*) qAnitya "$entry" ;;
        esac
    done
}


# ### Main Section
if [ "$0" = "${BASH_SOURCE[0]}" ];then
    VersionQuery "$@"
fi
