#!/bin/bash
set -euo pipefail

# shellcheck source=../pkg.lists.sh
source "${BASH_SOURCE[0]%/*}/../pkg.lists.sh"

query_aur () {
    local url="${1}"
    local pkgver="null"
    local tmpdir
    tmpdir="$(mktemp -d)"

    git clone --quiet --depth=1 "$url" "$tmpdir"
    
    # shellcheck disable=1091
    source "${tmpdir}/PKGBUILD" || :
    echo "${pkgver}"
}

query_github_release () {
    local url="${1/github.com/api.github.com/repos}/releases/latest"
    curl -s "$url" | jq -r .tag_name
}

query_github_tag () {
    local url="${1/github.com/api.github.com/repos}/tags"
    curl -s "$url" | jq -r '.[0].name'
}

# Actions

QURL () {
    local url="$1"

    case "$url" in
        https://github.com/?*) query_github_tag "$url" ;;
        https://aur.archlinux.org/?*.git) query_aur "$url" ;;
    esac
}

QReleaseMonitor_Org () {
    local project="$1"
    curl -s "https://release-monitoring.org/api/v2/projects/?name=${project}" | jq -r '.items[0].stable_versions[0]'
}

ScriptlessQuery () {
    local pkg upstream_url rel_mon_project

    for pkg in "$@"; do
        pkg="${pkg##*/}"
        
        upstream_url="${PkgUpstreamURLs[$pkg]:-null}"
        rel_mon_project="${PkgProjectNameOverrides[$pkg]:-$pkg}"

        if [ "${upstream_url}" != "null" ]; then
            QURL "$upstream_url"

        else
            QReleaseMonitor_Org "$rel_mon_project"

        fi
    done
}

# ### Main Function
VersionQuery () {
    local pkg

    for pkg in "$@"; do
        pkg="${pkg##*/}"
        [ -x "${0%/*}/VersionQuery/$pkg" ] && exec "${0%/*}/VersionQuery/$pkg"
        
        ScriptlessQuery "$pkg"
    done
}


# ### Main Section
if [ "$0" = "${BASH_SOURCE[0]}" ];then
    VersionQuery "$@"
fi
