#!/bin/bash

# ### Env
set -euo pipefail
ThisScript="$(realpath -- "$0")"
RepoPath="${ThisScript%/*/*}"

cd "$RepoPath"
ThisRepo="${THIS_REPO}"

WorkDir="$(mktemp -d)"

CleanUp () {
    rm -rf "${WorkDir?}"
}

trap CleanUp EXIT

# Mitigate potential security issue (scripts sourced by `get-latest-version`)

obsToken="$OBS_TOKEN"
obsCredentials="$OBS_CREDENTIALS"
obsAPI="${OBS_API:-api.opensuse.org}"

mapfile -tu3 ProjectList 3<<< "$OBS_PROJECT_LIST"
exec 3<&-

unset OBS_TOKEN OBS_CREDENTIALS THIS_REPO OBS_PROJECT_LIST

# ### Methods
# ========= Print Functions ===========
PrintOK () {
    echo "[+] $*" >&2
}

PrintInfo () {
    echo "[i] $*" >&2
}

PrintNote () {
    echo "[*] $*" >&2
}

PrintWarning () {
    echo "[-] $*" >&2
}

PrintError () {
    echo "[x] $*" >&2
}
# ==================================================

# Calls `curl` with OBS Credentials
curl_cr () {
    local -x local_obs_credentials="$obsCredentials"

    curl -s \
        -K <(printenv local_obs_credentials | sed 's/"/\\"/;s/^.*$/user = "&"/') \
        -H "Accept: application/xml; charset=utf-8" \
        "$@"
}

# Calls `curl` with OBS Token
curl_t () {
    local -x local_obs_token="$obsToken"

    curl -s \
        -K <(printenv local_obs_token | sed 's/^.*$/header = "Authorization: Token &"/') \
        -H "Accept: application/xml; charset=utf-8" \
        "$@"
}

ServiceRunRequestToken () {
    local project="$1"
    local package="$2"

    PrintInfo "Sending a ServiceRun request to OBS for: $package"
	curl_t \
		-X POST "https://$obsAPI/trigger" \
		-d "project=$project&package=$package" \

	printf '\n'
}

ServiceRunRequest () {
    local project_name="$1"
    local package_name="$2"
    local new_version="$3"
    local comment="RunService: version pump to ${new_version}"

    PrintInfo "Sending a ServiceRun request to OBS for: $package ($new_version)"
    curl_cr \
        -X POST "https://$obsAPI/source/${project_name}/${package_name}" \
        -F "cmd=runservice" \
        -F "comment=$comment"

    printf '\n'
}

ListProjectPackages () {
    local project_name="$1"

    # Just incase the project list ends with an empty line
    [ -z "$*" ] && return 0

    curl_cr "https://$obsAPI/source/$project_name" | xmlstarlet select -t -v "/directory/entry/@name" -n
}

ListPackageFiles () {
    local project_name="$1"
    local package_name="$2"

    # Just incase the project list ends with an empty line
    [ -z "$*" ] && return 0
    curl_cr "https://$obsAPI/source/$project_name/$package_name" | xmlstarlet select -t -v "/directory/entry/@name" -n
}

get_pkg_info () {
    local key="$1"
    local pki_file="$2"

    perl -nle "print \$2 if /^($key):\s*([^\s]*)$/" "${pki_file}"
}

set_pkg_info () {
    local key="$1"
    local value="$2"
    local pki_file="$3"

    sed -Ei "/^${key}:/s|[^[:space:]]*$|${value}|" "${pki_file}"
}

HandlePackage__pkg_info () {
    local project_name="$1"
    local package_name="$2"
    local file_name="_pkg_info"

    local old_version new_version upstream
    local comment pkg_info_file

    pkg_info_file="$(mktemp -p "$WorkDir")"
    curl_cr \
        --output "${pkg_info_file}" \
        "https://$obsAPI/source/${project_name}/${package_name}/${file_name}"


    upstream="$(get_pkg_info Upstream "${pkg_info_file}")"
    old_version="$(get_pkg_info Version "${pkg_info_file}")"
    new_version="$("${0%/*}/get-latest-version" "${upstream:-${package_name}}")"

    if [ "${new_version:?}" = null ]; then
        PrintError "Unknown Version: $package_name"
        return 1
    fi

    if [ "${new_version:?}" = "${old_version:?}" ]; then
        PrintOK "UptoDate: $package_name ($new_version)"
        return 0
    fi

    # Set `Version:` in _pkg_info to new version
    PrintNote "Update: $package_name ($old_version => $new_version)"
    set_pkg_info Version "${new_version}" "${pkg_info_file}"

    comment="${ThisRepo##*/}: version pump to ${new_version}"

    PrintInfo "Uploading ${file_name}..."
    curl_cr \
        -T "${pkg_info_file}" \
        "https://$obsAPI/source/${project_name}/${package_name}/${file_name}?comment=$(jq -s -R -r @uri <<< "$comment")"
}

get_pkginfo_servicefile () {
    local key="$1"
    local svfile="$2"

    perl -nle "print \$2 if /^\s*<!--\s*($key): \s*([^\s]*)\s*-->\s*$/" "${svfile}"
}

write_service_file () {
    # Reads: project_name, package_name, new_version
    local -x Project="${project_name:?}"
    local -x Name="${package_name:?}"
    local -x Version="${new_version:?}"
    local -x SaneVersion="${new_version//[^a-zA-Z0-9._+]/_}"
    local -x NumVersion="${new_version//[^0-9.]/}"

    NumVersion="$(sed -r 's/\.+/./g;s/(^\.|\.$)//g' <<< "${NumVersion}")"

    envsubst < "${1}" > "${2}"
}

HandlePackage__service () {
    local project_name="$1"
    local package_name="$2"
    local service_file
    local service_file_in

    local old_version new_version upstream
    local work_dir

    work_dir="$(mktemp -d)"
    service_file="${work_dir}/_service"
    service_file_in="${work_dir}/_service.in"

    local i
    for i in _service _service.in ;do
        curl_cr \
            --output "${work_dir}/${i}" \
            "https://$obsAPI/source/${project_name}/${package_name}/${i}"
    done

    upstream="$(get_pkginfo_servicefile Upstream "$service_file")"
    old_version="$(get_pkginfo_servicefile Version "$service_file")"
    new_version="$("${0%/*}/get-latest-version" "${upstream:-${package_name}}")"

    # xmlstarlet select -t -v "/services/service[@name='set_version']/param[@name='version']" "$service_file"

    if [ "${new_version:?}" = null ]; then
        PrintError "Unknown Version: $package_name"
        return 1
    fi

    if [ "${new_version:?}" = "${old_version:?}" ]; then
        PrintOK "UptoDate: $package_name ($new_version)"
        return 0
    fi

    # Write the new _service file
    PrintNote "Update: $package_name ($old_version => $new_version)"
    write_service_file "${service_file_in}" "${service_file}"

    comment="${ThisRepo##*/}: version pump to ${new_version}"

    PrintInfo "Uploading ${service_file##*/}..."
    curl_cr \
        -T "${service_file}" \
        "https://$obsAPI/source/${project_name}/${package_name}/${service_file##*/}?comment=$(jq -s -R -r @uri <<< "$comment")"
}

HandlePackage () {
    local project_name="$1"
    local package_name="$2"
    local pkg_files file_name

    pkg_files="$(ListPackageFiles "$project_name" "$package_name")"

    local f
    for f in _service.in _pkg_info; do
        grep -Fxq -- "${f}" <<< "$pkg_files" && file_name="$f"
    done

    case "${file_name:-null}" in
        _service.in) HandlePackage__service "$@" ;;
        _pkg_info) HandlePackage__pkg_info "$@" ;;
        *)
            PrintInfo "Skipping un-managed package: $package_name"
            return 0
        ;;
    esac
}

ValidateCredentials () {
    local obs_user="${obsCredentials%%:*}"
    local response token_count token_id token_description

    response="$(curl_cr "https://$obsAPI/person/$obs_user/token")"
    token_count="$(xmlstarlet select -t -v "/directory/@count" -n <<< "$response" 2> /dev/null)"

    if [ -z "$token_count" ]; then
        PrintError "Invalid Response"
        echo "$response" >&2
        exit 202
    fi


    PrintOK "Credentials validated"
    [ "${token_count}" -eq 0 ] && PrintWarning "OBS Token was not validated (user has no OBS tokens)" && return 0

    # FIXME: Exposure in arguments
    token_id="$(xmlstarlet select -t -v "/directory/entry[@string = '$obsToken']/@id" -n <<< "$response")"
    [ -z "$token_id" ] && PrintWarning "OBS Token was not validated" && return 0

    token_description="$(xmlstarlet select -t -v "/directory/entry[@id = '$token_id']/@description" -n <<< "$response")"
    PrintOK "OBS Token validated: $token_description"
}

# ========== Main Section ============
ValidateCredentials

for project in "${ProjectList[@]}"; do

    while read -ru3 package;do
        HandlePackage "$project" "$package" || :
    done 3< <(ListProjectPackages "$project")
    exec 3<&-

done
