#!/bin/bash

# ### Env
set -euo pipefail
KeyName="VERSIONSBASE64"
ThisScript="$(realpath -- "$0")"
RepoPath="$(dirname "$ThisScript" | xargs dirname)"
export PATH="${RepoPath}/util:$PATH"

cd "$RepoPath"
ThisRepo="${THIS_REPO}"

OldCatalogFile="$(mktemp)"
NewCatalogFile="$(mktemp)"

# PackageList="$(awk '/^[^#]*$/{print $1}' service-run.list manual.list | tr '\n' ' ')"
mapfile -d $'\n' -t ServiceRunPackages < <(awk '/^[^#]*$/{print $1}' service-run.list)
mapfile -d $'\n' -t ManualPackages < <(awk '/^[^#]*$/{print $1}' manual.list)
PackageList=("${ServiceRunPackages[@]}" "${ManualPackages[@]}")


# Mitigate potential security issue (scripts sourced by `get-latest-version`)
AccessVariablesToken="$ACCESS_VARIABLES_TOKEN"
obsHome="$OBS_HOME_PROJECT"
obsToken="$OBS_TOKEN"
obsCredentials="$OBS_CREDENTIALS"

export ACCESS_VARIABLES_TOKEN=""
export OBS_HOME_PROJECT=""
export OBS_TOKEN=""
export OBS_CREDENTIALS=""
export THIS_REPO=""

# ### Methods
# Print
PrintOK () {
    echo "[+] $*" >&2
}

PrintInfo () {
    echo "[i] $*" >&2
}

PrintNote () {
    echo "[*] $*" >&2
}

PrintWarning () {
    echo "[-] $*" >&2
}

PrintError () {
    echo "[x] $*" >&2
}

UpdateOnlineStore () {
    PrintInfo "Updating online store..."
    
    curl -s -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $AccessVariablesToken" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d "{\"name\":\"${KeyName}\",\"value\":\"$(base64 -w0 "$NewCatalogFile")\"}" \
        "https://api.github.com/repos/$ThisRepo/actions/variables/${KeyName}"
}

FetchOnlineStore () {
    PrintInfo "Reading from online store..."

    curl -s -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $AccessVariablesToken" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/repos/$ThisRepo/actions/variables/${KeyName}" | jq -r .value | base64 -d > "$OldCatalogFile"
}

# Generate New Catalog
GenNewCatalog () {
    local pkg project_url latest_version
    rm -f "$NewCatalogFile"

    PrintInfo "Checking for version updates..."
    git config --global init.defaultBranch master &> /dev/null

    for pkg in "${PackageList[@]}";do
        project_url="$(awk "/^${pkg//\//\\\/}/{print \$2}" ./*.list | head -n1)"
        latest_version="$(get-latest-version "$project_url")"
        
        echo "$pkg $latest_version" >> "$NewCatalogFile"
    done
}

ServiceRunRequestToken () {
    local project="$1"
    local package="$2"

    PrintInfo "Sending a ServiceRun request to OBS for: $package"
	curl -sH "Authorization: Token $obsToken" \
			-H "Accept: application/xml; charset=utf-8" \
			-X POST "https://api.opensuse.org/trigger" \
			-d "project=$project&package=$package"

	printf '\n'
}

ServiceRunRequest () {
    local project_name="$1"
    local package_name="$2"
    local new_version="$3"
    local comment="RunService: version pump to ${new_version}"

    PrintInfo "Sending a ServiceRun request to OBS for: $package ($new_version)"
    curl -sH "Accept: application/xml; charset=utf-8" \
            --user "${obsCredentials}" \
            -X POST "https://api.opensuse.org/source/${project_name}/${package_name}" \
            -F "cmd=runservice" \
            -F "comment=$comment"
    
    printf '\n'
}

ManualUpdate () {
    local project_name="$1"
    local package_name="$2"
    local new_version="$3"
    local comment="version pump to ${new_version}"
    local file_name="${package_name}.spec"
    
    local temp_spec
    temp_spec="$(mktemp)"

    PrintInfo "Fetching ${file_name}..."
    curl --silent --output "${temp_spec}" \
            --user "${obsCredentials}" \
            -H "Accept: application/xml; charset=utf-8" \
            -X GET "https://api.opensuse.org/source/${project_name}/${package_name}/${file_name}"

    # Set `Version:` in specfile to new version
    PrintInfo "Setting version to ${new_version}..."
    sed -i -r "/^Version: */s| [^ ]*$| ${new_version}|" "${temp_spec}"

    PrintInfo "Uploading ${file_name}..."
    curl --silent --upload-file "${temp_spec}" \
            --user "${obsCredentials}" \
            -H "Accept: application/xml; charset=utf-8" \
            "https://api.opensuse.org/source/${project_name}/${package_name}/${file_name}?comment=$(jq -s -R -r @uri <<< "$comment")"

    
    rm -f "${temp_spec}"
}

set_package () {
    local project_and_pkg="$1"

    case "$project_and_pkg" in
        */*) project_and_pkg="Home:$project_and_pkg" ;;
        *) project_and_pkg="Home/$project_and_pkg";;
    esac
    
    PrintInfo "Sending a ServiceRun request to OBS for: $project_and_pkg"
    project_and_pkg="$obsHome${project_and_pkg#Home}"

    # Global scpoe
    project="${project_and_pkg%/*}"
    package="${project_and_pkg#*/}"
}

get_package_version () {
    local old_or_new="$1"
    local package_name="$2"
    local catalog_file

    if [ "${old_or_new}" = "--old" ];then
        catalog_file="$OldCatalogFile"

    elif [ "${old_or_new}" = "--new" ];then
        catalog_file="$NewCatalogFile"
    
    else
        exit 50
    fi

    awk "/^${package_name//\//\\\/}/{print \$2}" "$catalog_file"
}

got_updated () {
    local package="$1"

    # set in global scope
    old_version="$(get_package_version --old "${package}")"
    new_version="$(get_package_version --new "${package}")"
    
    if [ "$old_version" != "$new_version" ];then
        if [ -z "$old_version" ];then
            PrintNote "New Entry: $package ($new_version)"
        else
            PrintNote "Update: $package ($old_version => $new_version)"
        fi

        return 0
    else
        PrintOK "Latest: $package ($old_version)"
        return 1
    fi
}

MakeRequestsAsNeeded () {
    local pkg
    local project package
    local old_version new_version

    for pkg in "${ServiceRunPackages[@]}";do
        if got_updated "$pkg";then
            set_package "$pkg"
            ServiceRunRequest "$project" "$package" "${new_version#[rv]}"
        fi
    done

    for pkg in "${ManualPackages[@]}";do
        if got_updated "$pkg";then
            set_package "$pkg"
            ManualUpdate "$project" "$package" "${new_version#[rv]}"
        fi
    done
}


# ### Main Section
FetchOnlineStore
GenNewCatalog
MakeRequestsAsNeeded
UpdateOnlineStore
