name: Update Signal
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5,17 * * *'

jobs:
  PackageTrigger:
      runs-on: ubuntu-latest

      steps:
      - name: Fetching Sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Installing dependancies
        run: |
          git config --global init.defaultBranch master &> /dev/null
          sudo apt install -y xmlstarlet

      - name: Sending requests to OBS for updated packages
        run: |
          util/pkg-trigger

        env:
            OBS_PROJECT_LIST: ${{ secrets.OBS_PROJECT_LIST }}
            OBS_TOKEN: ${{ secrets.OBS_TOKEN }}
            OBS_CREDENTIALS: ${{ secrets.OBS_CREDENTIALS }}
            THIS_REPO: ${{ github.repository }}
