name: Update Signal
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5,17 * * *'

jobs:
  OnlineRefresh:
      runs-on: ubuntu-latest

      steps:
      - name: Fetching Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Sending requests to OBS for updated packages
        run: |
          util/refresh-catalog

        env:
            ACCESS_VARIABLES_TOKEN: ${{ secrets.ACCESS_VARIABLES_TOKEN }}
            OBS_HOME_PROJECT: ${{ secrets.OBS_HOME_PROJECT }}
            OBS_TOKEN: ${{ secrets.OBS_TOKEN }}
            OBS_CREDENTIALS: ${{ secrets.OBS_CREDENTIALS }}
            THIS_REPO: ${{ github.repository }}
